[tool.poetry]
name = "fergana"
version = "0.0.1"
description = "Simple Ml framework"
authors = ["egor-mashtakov <egor190707e@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"



[build-system]
requires = ["poetry-core"]
